### ISSUE TITLE
请问需要使用stm32吗？

### ISSUE THREAD

**Issue by tenoms** [the-light011/Face-Mask-detction-DeepLearning#1]
作者你好，请问这个项目需要用带stm32吗？
内部图片后面那块底板是什么呢？纯新人🙃

**Comment by lightyLi** [comment]
@zgytlkj  hello,因为这个需要很大的算力,stm32的话延迟会有点高.我们用的是k210,有浮点加速芯片,延迟比较低.
内部图片底板就是一个面包板,用来固定的

**Comment by tenoms** [comment]
😇感谢你的开源，折腾几天，基本上完成了，哈哈

**Comment by lightyLi** [comment]
@zgytlkj 不错哦！
