### ISSUE TITLE
作者你好，请问你有解决多线程问题吗？

### ISSUE THREAD

**Issue by tenoms** [the-light011/Face-Mask-detction-DeepLearning#2]
@lightyLi hello，请问你后来有解决多线程的问题吗？我现在遇到的问题是会等待语音播报结束才开始运行检测，我尝试使用_thread，不报错，但就是不执行_thread中的函数😭

**Comment by lightyLi** [comment]
@zgytlkj hey, 应该是没有，thread模块是编译进固件的，可以在网站上把自己需要的固件编译进固件里。
多线程，当时试验的时候，我记得也是声音播放会阻塞线程，和不用多线程没有区别，就没用。我觉得这是硬件上造成的吧，不清楚，你可以再研究一下.

还有一个问题，由于板子内存太小，所以固件体积就比较小，稍微编译一点其他模块就会超出大小限制，导致有些功能出错
